### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by tylerkrupicka** [intuit/postcss-themed#18]
This project is one of the few projects that are perfect for testing and test-driven-development. While we have high test coverage, I'm sure there are many test cases we could add. 

If you can increase our test coverage at all we'd really appreciate it!

**Comment by ratnamal** [comment]
@tylerkrupicka I took a look at this issue. Created a PR with my changes and ready for review

**Comment by yoqwerty** [comment]
Hi @tylerkrupicka @adierkens, I took a stab at improving the code coverage a little more. Have raised the PR, please review when you have a moment.
Thanks!
Pull request - https://github.com/intuit/postcss-themed/pull/68
