### ISSUE TITLE
Add Logo

### ISSUE THREAD

**Issue by tylerkrupicka** [intuit/postcss-themed#19]
Are you a designer looking to contribute to this project? Our ReadMe looks a little plain without a logo to showcase the theming capabilities. Please feel free to contribute! 

Bonus points if you can make it support GitHub in light and dark mode.

**Comment by mandyellow** [comment]
Hello! I made a logo for your project. Let me know if you like it so I can open a PR with the PNG and an SVG to you. 🦊

![image](https://user-images.githubusercontent.com/30158643/94853628-0da07f80-0402-11eb-9356-532a845cfbb5.png)

**Comment by tylerkrupicka** [comment]
@mandyellow Yeah please open a PR! I personally like the one on the left better, but both are great! If you can, add an `images` folder to the repo, add your images there (feel free to include both since you made them, svg and png are fine). Then add the logo to the readme! 

If you add alt text to the logo we can probably remove the "PostCSS Themed" title from the top of the readme. 

Thanks!

**Comment by tylerkrupicka** [comment]
Resolved by https://github.com/intuit/postcss-themed/pull/33. Thanks @mandyellow @Sharps for the great work!
