### ISSUE TITLE
Use Auto All Contributors 

### ISSUE THREAD

**Issue by tylerkrupicka** [intuit/postcss-themed#21]
This project uses [intuit/auto](https://github.com/intuit/auto/) to manage releases on GitHub. A while back, we added an [all-contributors](https://github.com/intuit/auto/tree/master/plugins/all-contributors) plugin for Auto that automatically adds new project contributors to the ReadMe. 

I'd be happy to review a PR to configure that plugin on this project!

**Comment by shubhamarora** [comment]
@tylerkrupicka Can I give this a shot?

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v2.0.3 :rocket:
