### ISSUE TITLE
New-line @theme causes build to hang

### ISSUE THREAD

**Issue by kharrop** [intuit/postcss-themed#45]
**Describe the bug**

If a user has prettier installed with a max-line width, sometimes @theme [variable] can wrap to multiple lines. This causes the build to hang indefinitely with no indication of what's wrong. It's especially noticeable if the line in question has animation-related css.

`/* prettier-ignore */` fixes this issue, but it can be pretty tedious to include this each time.

**To Reproduce**

Break up a line of css where @theme and the variable are on separate lines.

**Expected behavior**

Either it just works, or the build tells you where something is failing.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 1.1.0

**Additional context**

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v2.4.2 :rocket:
